version: "3.9"
services:
  ml_app:
    build:
      context: .
    # restart: always
    ports:
      - 8001:8001
    volumes:
      - ./app:/app
    environment:
      - DEBUG=0
    # command: tail -F anything
    command: sh -c "python fused_inferencer.py"
