# Generated by Django 3.2.18 on 2023-02-23 02:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerecord',
            name='ir_image',
        ),
        migrations.RemoveField(
            model_name='imagerecord',
            name='rgb_image',
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
