# Generated by Django 3.2.18 on 2023-02-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerecord',
            name='status',
            field=models.CharField(choices=[('Viewed', 'Viewed'), ('Visited', 'Visited'), ('Dismissed', 'Dismissed'), ('Not viewed', 'Notviewed')], default='Not viewed', max_length=20),
        ),
    ]
