# Generated by Django 3.2.18 on 2023-02-27 04:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_imagerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerecord',
            name='image_masked',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
