# Generated by Django 3.2.18 on 2023-02-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.AddField(
            model_name='location',
            name='path',
            field=models.IntegerField(default=-1),
        ),
    ]
