# Generated by Django 3.2.18 on 2023-02-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230225_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotspot',
            old_name='record_id',
            new_name='record',
        ),
    ]
